name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 tmp folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "index.html"
          target: "/tmp/deploy"

      - name: Move files into nginx folder with sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo mv /tmp/deploy/* /usr/share/nginx/html/
            sudo chown -R nginx:nginx /usr/share/nginx/html
